 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container franklaercio-db-1  Creating
 Container franklaercio-db-1  Created
 Container franklaercio-api01-1  Creating
 Container franklaercio-api02-1  Creating
 Container franklaercio-api02-1  Created
 Container franklaercio-api01-1  Created
 Container franklaercio-nginx-1  Creating
 Container franklaercio-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-22 02:49:07.582 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-22 02:49:07.585 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-22 02:49:07.594 UTC [51] LOG:  database system was shut down at 2024-02-22 02:49:07 UTC
db-1     | 2024-02-22 02:49:07.600 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
db-1     | CREATE TABLE
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db-1     | CREATE TABLE
db-1     | INSERT 0 1
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | 
db-1     | 
db-1     | 2024-02-22 02:49:07.835 UTC [48] LOG:  received fast shutdown request
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
db-1     | waiting for server to shut down....2024-02-22 02:49:07.838 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-22 02:49:07.839 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-22 02:49:07.840 UTC [49] LOG:  shutting down
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | 2024-02-22 02:49:07.848 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-22 02:49:08.350 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.382 s, sync=0.099 s, total=0.511 s; sync files=307, longest=0.075 s, average=0.001 s; distance=4294 kB, estimate=4294 kB; lsn=0/191C400, redo lsn=0/191C400
db-1     | 2024-02-22 02:49:08.355 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-22 02:49:08.463 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-22 02:49:08.463 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-22 02:49:08.463 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-22 02:49:08.468 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-22 02:49:08.476 UTC [66] LOG:  database system was shut down at 2024-02-22 02:49:08 UTC
db-1     | 2024-02-22 02:49:08.483 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/22 02:49:10 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.28.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:10 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.28.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:12 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:14 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-22T02:49:15.221Z  INFO 1 --- [           main] com.github.rinha.Application             : Starting Application v1.0.0 using Java 21.0.1 with PID 1 (/app/app.jar started by root in /)
api02-1  | 2024-02-22T02:49:15.226Z  INFO 1 --- [           main] com.github.rinha.Application             : No active profile set, falling back to 1 default profile: "default"
api01-1  | 2024-02-22T02:49:15.327Z  INFO 1 --- [           main] com.github.rinha.Application             : Starting Application v1.0.0 using Java 21.0.1 with PID 1 (/app/app.jar started by root in /)
api01-1  | 2024-02-22T02:49:15.333Z  INFO 1 --- [           main] com.github.rinha.Application             : No active profile set, falling back to 1 default profile: "default"
nginx-1  | 2024/02/22 02:49:16 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:18 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:20 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:22 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.28.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:22 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.28.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:24 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:26 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:28 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-22T02:49:29.318Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
api02-1  | 2024-02-22T02:49:29.421Z  INFO 1 --- [           main] com.github.rinha.Application             : Started Application in 18.498 seconds (process running for 22.632)
api01-1  | 2024-02-22T02:49:29.524Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
api01-1  | 2024-02-22T02:49:29.622Z  INFO 1 --- [           main] com.github.rinha.Application             : Started Application in 18.101 seconds (process running for 22.182)
nginx-1  | 2024/02/22 02:49:30 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/22 02:49:32 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-22T02:49:35.122Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api02-1  | 2024-02-22T02:49:36.521Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@7aa76749
api02-1  | 2024-02-22T02:49:36.523Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api01-1  | 2024-02-22T02:49:43.925Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api01-1  | 2024-02-22T02:49:45.714Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@95f1e35
api01-1  | 2024-02-22T02:49:45.717Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1  | 2024-02-22T02:53:55.655Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01-1  | 2024-02-22T02:53:55.664Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api02-1  | 2024-02-22T02:53:55.665Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api01-1  | 2024-02-22T02:53:55.671Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api01-1 exited with code 0
api01-1 exited with code 143
api02-1 exited with code 0
api02-1 exited with code 143
db-1     | 2024-02-22 02:53:56.430 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-22 02:53:56.434 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-22 02:53:56.435 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-22 02:53:56.436 UTC [64] LOG:  shutting down
db-1     | 2024-02-22 02:53:56.438 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-22 02:53:56.579 UTC [64] LOG:  checkpoint complete: wrote 623 buffers (3.8%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.009 s, sync=0.116 s, total=0.144 s; sync files=31, longest=0.109 s, average=0.004 s; distance=16781 kB, estimate=16781 kB; lsn=0/297FBB8, redo lsn=0/297FBB8
db-1     | 2024-02-22 02:53:56.583 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
